### ISSUE TITLE
Can't register org.bukkit.scoreboard.Team with the code name team because that name is already used by types.team

### ISSUE THREAD

**Issue by SsoCG0111** [TheLimeGlass/Skellett#106]
I used Google Translate

Error occurred while enabling Skellett v1.9.9 (Is it up to date?)
java.lang.IllegalArgumentException: Can't register org.bukkit.scoreboard.Team with the code name team because that name is already used by types.team
	at ch.njol.skript.registrations.Classes.registerClass(Classes.java:90) ~[?:?]
	at com.gmail.thelimeglass.Register.types(Register.java:690) ~[?:?]
	at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:200) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[09:05:15] [Server thread/INFO]: [Skellett] Disabling Skellett v1.9.9

It is paper 1.12.2

The list of addons is

SkEtcR v2.2
Sk-NBeeT
skRayFall+v1.9.21
SkQuery-4.1.2
skript-yaml
SkRPG-Lime
Skellett-Legacy
skDragon
SharpSK
SkrayFall+v 1.9.21
skUtilities.v0.9.2

**Comment by TheLimeGlass** [comment]
duplicate #92
