### ISSUE TITLE
Client World Border (1.12.2)

### ISSUE THREAD

**Issue by Sun3nas** [TheLimeGlass/Skellett#107]
Using: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Skript: 2.5-beta3, Skellet: 1.9.9

[20:47:24] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:47:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:47:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:47:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:47:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ReflectionSyntax.ClientBorderManager.getBorderPacket(ClientBorderManager.java:54)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ReflectionSyntax.ClientBorderManager.setCenter(ClientBorderManager.java:94)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ClientBorders.ExprClientBorderCenter.change(ExprClientBorderCenter.java:60)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.effects.EffChange.execute(EffChange.java:283)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.Commands.handleCommand(Commands.java:249)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:166)
[20:47:24] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[20:47:24] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:47:24] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:47:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[20:47:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:47:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:47:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[20:47:24] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayOutWorldBorder.<init>(PacketPlayOutWorldBorder.java:22)
[20:47:24] [Server thread/WARN]: 	... 33 more
[20:47:24] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:47:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:47:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:47:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:47:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ReflectionSyntax.ClientBorderManager.getBorderPacket(ClientBorderManager.java:54)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ReflectionSyntax.ClientBorderManager.setSize(ClientBorderManager.java:67)
[20:47:24] [Server thread/WARN]: 	at com.gmail.thelimeglass.ClientBorders.ExprClientBorderSize.change(ExprClientBorderSize.java:65)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.effects.EffChange.execute(EffChange.java:283)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.Commands.handleCommand(Commands.java:249)
[20:47:24] [Server thread/WARN]: 	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:166)
[20:47:24] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[20:47:24] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:47:24] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:47:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1484)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[20:47:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:47:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:47:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[20:47:24] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[20:47:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayOutWorldBorder.<init>(PacketPlayOutWorldBorder.java:22)
[20:47:24] [Server thread/WARN]: 	... 33 more

**Comment by TheLimeGlass** [comment]
Client borders are going to be removed, and put into Skacket. They don't support 1.12+
