### ISSUE TITLE
1.10.2(latest) Error :(

### ISSUE THREAD

**Issue by GreatRaceofGithub** [TheLimeGlass/Skellett#11]
Hi.

[18:22:04] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Skellett v1.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1861) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.gmail.thelimeglass.Command.onInventoryClick(Command.java:54) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor255.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 15 more

**Comment by TheLimeGlass** [comment]
I believe I have fixed this issue in the next update.

I'm not quite sure where it's coming from. I can't reproduce the error.

Can you explain when it happens?
