### ISSUE TITLE
Error occurred while enabling

### ISSUE THREAD

**Issue by arts7493** [TheLimeGlass/Skellett#110]
15:31:00] [Server thread/ERROR]: Error occurred while enabling Skellett v1.9.10 (Is it up to date?)
ch.njol.skript.SkriptAPIException: No class info found for team
	at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263) ~[?:?]
	at com.gmail.thelimeglass.Register.types(Register.java:696) ~[?:?]
	at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:200) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[15:31:00] [Server thread/INFO]: [Skellett] Disabling Skellett v1.9.10

**Comment by Govindass** [comment]
I am having the same issue on 1.12.2 Paper

**Comment by the-najjar** [comment]
same issue on paper 1.16.3 latest version, and Skellet V1.19.10 and Skript 2.5

**Comment by Govindass** [comment]
> 
> 
> same issue on paper 1.16.4 latest version, and Skellet V1.19.10 and Skript 2.5

1.16.4??? you're living in the future
