### ISSUE TITLE
An error occurs while loading the plugin in version 1.16.3

### ISSUE THREAD

**Issue by Quant-TheodoreFelix** [TheLimeGlass/Skellett#112]
[20:21:52 ERROR]: Error occurred while enabling Skellett v1.9.10 (Is it up to date?)
ch.njol.skript.SkriptAPIException: No class info found for team
        at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263) ~[?:?]
        at com.gmail.thelimeglass.Register.types(Register.java:696) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:200) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.3-latest.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Have you not yet supported version 1.16.3?**

**Comment by SpeedBlock** [comment]
I have the same problem, I think he has to fix parts of the code because the problem is not ours

**Comment by Quant-TheodoreFelix** [comment]
> I have the same problem, I think he has to fix parts of the code because the problem is not ours

Skellett 1.9.9 works without errors, but add-ons are not available :(

**Comment by TheLimeGlass** [comment]
fixed 1.9.11

**Comment by Quant-TheodoreFelix** [comment]
> fixed 1.9.11

Thank you :)
