### ISSUE TITLE
1.10.2(latest) Error #2

### ISSUE THREAD

**Issue by GreatRaceofGithub** [TheLimeGlass/Skellett#12]
Excuse my succession.
[22:14:32] [Server thread/ERROR]: #!#! Current node: null
[22:14:32] [Server thread/ERROR]: #!#! Current item: "%[the] [skellett] (title|name|header|string) of [boss[ ]]bar %bossbar%%" is equal to "Radiation" (comparator: ch.njol.skript.classes.data.DefaultComparators$14@268d921)
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! Thread: Server thread
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! End of Error.
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:14:32] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:14:32] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[22:14:32] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:14:32] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:14:32] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:14:32] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:14:32] [Server thread/ERROR]: #!#! 
[22:14:32] [Server thread/ERROR]: #!#! Stack trace:
[22:14:32] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[22:14:32] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.BossBars.ExprBarTitle.get(ExprBarTitle.java:42)
[22:14:32] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.BossBars.ExprBarTitle.get(ExprBarTitle.java:1)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getAll(VariableString.java:493)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.check(VariableString.java:508)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:260)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:91)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:109)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[22:14:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[22:14:32] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:953)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:14:32] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:14:32] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[22:14:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[22:14:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)

**Comment by TheLimeGlass** [comment]
The bossbar isn't set. Added a nullpointer check so this error doesn't happen but instead return <none>
