### ISSUE TITLE
Length of Hitbox is not working on paper 1.16.5

### ISSUE THREAD

**Issue by miglas** [TheLimeGlass/Skellett#121]
java.lang.NoSuchFieldException: length
[21:11:59 WARN]:        at java.lang.Class.getField(Unknown Source)
[21:11:59 WARN]:        at com.gmail.thelimeglass.Expressions.ExprHitboxLength.get(ExprHitboxLength.java:51)
[21:11:59 WARN]:        at com.gmail.thelimeglass.Expressions.ExprHitboxLength.get(ExprHitboxLength.java:21)
[21:11:59 WARN]:        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[21:11:59 WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:276)
[21:11:59 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:51)
[21:11:59 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[21:11:59 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[21:11:59 WARN]:        at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
[21:11:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[21:11:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[21:11:59 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413)
[21:11:59 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418)
[21:11:59 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328)
[21:11:59 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116)
[21:11:59 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[21:11:59 WARN]:        at java.lang.Thread.run(Unknown Source)

version: Skellett 1.9.11
             Skript: 2.5.3
Code: 

on damage:
	attacker is player
	set {_hw} to victim's hitbox length
	message "%{_hw}%" to attacker

I cant get hitbox length of any mobs.

**Comment by TheLimeGlass** [comment]
Removed in 2.0.0
