### ISSUE TITLE
block hardness is not working on 1.16.5

### ISSUE THREAD

**Issue by ghost** [TheLimeGlass/Skellett#123]
```
[13:24:28] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.getBlock(org.bukkit.block.Block)
[13:24:28] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Utils.ReflectionUtil.getNMSBlock(ReflectionUtil.java:74)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.getHardness(ExprBlockHardness.java:89)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.get(ExprBlockHardness.java:54)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.get(ExprBlockHardness.java:26)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Condition.run(Condition.java:55)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.Function.execute(Function.java:135)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:51)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
[13:24:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:24:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[13:24:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[13:24:28] [Server thread/WARN]: java.lang.NoSuchFieldException: strength
[13:24:28] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.getHardness(ExprBlockHardness.java:90)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.get(ExprBlockHardness.java:54)
[13:24:28] [Server thread/WARN]: 	at com.gmail.thelimeglass.Expressions.ExprBlockHardness.get(ExprBlockHardness.java:26)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Condition.run(Condition.java:55)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.Function.execute(Function.java:135)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:51)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:24:28] [Server thread/WARN]: 	at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
[13:24:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[13:24:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
[13:24:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[13:24:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by TheLimeGlass** [comment]
It's in Skript now
