### ISSUE TITLE
1.16.5 Open Book 'Invalid book tag'

### ISSUE THREAD

**Issue by KuiDaXElaina** [TheLimeGlass/Skellett#126]
1.16.5 Open Book 'Invalid book tag'
![image](https://user-images.githubusercontent.com/42274557/123355356-18a2cd80-d598-11eb-83ce-4a995493730c.png)
![image](https://user-images.githubusercontent.com/42274557/123355381-25272600-d598-11eb-8e8c-0c3f55edb11a.png)
You will receive a warning in the background when executing the command
`[01:26:14 WARN]: java.lang.IllegalAccessException: class com.gmail.thelimeglass.Books.BungeeJson.EffAddComponentToPage cannot access a member of class org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaBook with modifiers "protected"
[01:26:14 WARN]:        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
[01:26:14 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
[01:26:14 WARN]:        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
[01:26:14 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:416)
[01:26:14 WARN]:        at com.gmail.thelimeglass.Books.BungeeJson.EffAddComponentToPage.execute(EffAddComponentToPage.java:50)
[01:26:14 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:51)
[01:26:14 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[01:26:14 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[01:26:14 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[01:26:14 WARN]:        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291)
[01:26:14 WARN]:        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[01:26:14 WARN]:        at ch.njol.skript.command.Commands.handleCommand(Commands.java:248)
[01:26:14 WARN]:        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[01:26:14 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[01:26:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:26:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:26:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131)
[01:26:14 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[01:26:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)`

In addition,'set author of book {_book} to "test"' is invalid syntax
![image](https://user-images.githubusercontent.com/42274557/123355556-78997400-d598-11eb-982c-163f9e56f0b7.png)

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0
