### ISSUE TITLE
Mysql Timeout, block all query

### ISSUE THREAD

**Issue by jewome62** [TheLimeGlass/Skellett#13]
Some days, i have error with Mysql query with Skellett

```
[20:43:17] [Server thread/INFO]: An internal error occurred while attempting to perform this command.
[20:43:17] [Server thread/INFO]: Heart-Craft [Admin]jewome62: stop click
[20:43:18] [Server thread/INFO]: MySQL Query:
[20:43:18] [Server thread/INFO]: Command: SELECT id, tool as itemTool, IFNULL(lore, '<none>') as itemLore, IFNULL(name, '<none>') as itemName, IFNULL(quantity, '<none>') as itemCount FROM skript_item WHERE uuid = '76eb7e87-e043-4c8d-91bd-b81fa3f22d7b' ORDER BY id LIMIT 36
[20:43:18] [Server thread/INFO]: Error: No operations allowed after connection closed.
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:43:18] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://forums.skunity.com/t/4148?u=nfell2009
[20:43:18] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[20:43:18] [Server thread/ERROR]: #!#! If not please reply with meaningful content, copy & paste this whole error into a pastebin (http://pastebin.com),
[20:43:18] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:43:18] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:43:18] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast. IF YOU DON'T FOLLOW IT, WE'LL HUNT YOU DOWN.
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! Stack trace:
[20:43:18] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[20:43:18] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.MySQL.ExprMySQLQueryInteger.get(ExprMySQLQueryInteger.java:45)
[20:43:18] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.MySQL.ExprMySQLQueryInteger.get(ExprMySQLQueryInteger.java:1)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:181)
[20:43:18] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
[20:43:18] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:43:18] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1055)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:150)
[20:43:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:43:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:43:18] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:43:18] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[20:43:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[20:43:18] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! Version Information:
[20:43:18] [Server thread/ERROR]: #!#!   Skript: 2.3
[20:43:18] [Server thread/ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[20:43:18] [Server thread/ERROR]: #!#!   Minecraft: 1.11.2
[20:43:18] [Server thread/ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[20:43:18] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.0-24-generic
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! Current node: null
[20:43:18] [Server thread/ERROR]: #!#! Current item: set {_idList::*}(as java.lang.Object) to [skellett] mysql integer %string% (in|from|of) %resultset%
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! Thread: Server thread
[20:43:18] [Server thread/ERROR]: #!#! 
[20:43:18] [Server thread/ERROR]: #!#! End of Error.
[20:43:18] [Server thread/ERROR]: #!#! 
```

And the first error is : 
```
[18:32:42] [Server thread/INFO]: MySQL Query:
[18:32:42] [Server thread/INFO]: Command: SELECT id, tool as itemTool, IFNULL(lore, '<none>') as itemLore, IFNULL(name, '<none>') as itemName, IFNULL(quantity, '<none>') as itemCount FROM skript_item WHERE uuid = '8d152925-db43-4e2f-ac77-dea0088c5726' ORDER BY id LIMIT 36
[18:32:42] [Server thread/INFO]: Error: The last packet successfully received from the server was 53,013,262 milliseconds ago.  The last packet sent successfully to the server was 53,013,262 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[18:32:42] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://forums.skunity.com/t/4148?u=nfell2009
[18:32:42] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[18:32:42] [Server thread/ERROR]: #!#! If not please reply with meaningful content, copy & paste this whole error into a pastebin (http://pastebin.com),
[18:32:42] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[18:32:42] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[18:32:42] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast. IF YOU DON'T FOLLOW IT, WE'LL HUNT YOU DOWN.
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! Stack trace:
[18:32:42] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[18:32:42] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.MySQL.ExprMySQLQueryInteger.get(ExprMySQLQueryInteger.java:45)
[18:32:42] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.MySQL.ExprMySQLQueryInteger.get(ExprMySQLQueryInteger.java:1)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:181)
[18:32:42] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
[18:32:42] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:32:42] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1055)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:150)
[18:32:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:32:42] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:32:42] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:32:42] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[18:32:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[18:32:42] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! Version Information:
[18:32:42] [Server thread/ERROR]: #!#!   Skript: 2.3
[18:32:42] [Server thread/ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[18:32:42] [Server thread/ERROR]: #!#!   Minecraft: 1.11.2
[18:32:42] [Server thread/ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[18:32:42] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.0-24-generic
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! Current node: null
[18:32:42] [Server thread/ERROR]: #!#! Current item: set {_idList::*}(as java.lang.Object) to [skellett] mysql integer %string% (in|from|of) %resultset%
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! Thread: Server thread
[18:32:42] [Server thread/ERROR]: #!#! 
[18:32:42] [Server thread/ERROR]: #!#! End of Error.
[18:32:42] [Server thread/ERROR]: #!#! 
```

Can you implement the autoReconnect=true ?
The connection is not available after /skript reload all
I must restart the server for fix the problem.

Thanks

**Comment by Martini002** [comment]
I am having this same problem.
autoReconnect is true in my config too

**Comment by CzEMC** [comment]
I still get this same error. I am certain that this is a bug. Making any queries to the database result in no data return.
