### ISSUE TITLE
Loading Chunks doesnt work

### ISSUE THREAD

**Issue by Pryzmm** [TheLimeGlass/Skellett#138]
when using the "load chunk" effect i get a big old error in console

[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! [Skript] Severe Error:
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Something went horribly wrong with Skript.
[01:36:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:36:57 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[01:36:57 ERROR]: #!#! Here is full list of them:
[01:36:57 ERROR]: #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) skript-gui v1.3-alpha3 (https://github.com/APickledWalrus/skript-gui) SkBee v1.11.4 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.0 (https://forums.skunity.com/resources/skellett.24/) 
[01:36:57 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[01:36:57 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[01:36:57 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[01:36:57 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[01:36:57 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[01:36:57 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Stack trace:
[01:36:57 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.load(boolean)" because the return value of "ch.njol.skript.lang.Expression.getSingle(org.bukkit.event.Event)" is null
[01:36:57 ERROR]: #!#!     at Skellett-Legacy-2.0.0.jar//com.gmail.thelimeglass.Effects.EffChunkLoad.execute(EffChunkLoad.java:39)
[01:36:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[01:36:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[01:36:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[01:36:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[01:36:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:36:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:36:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1564)
[01:36:57 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[01:36:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[01:36:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[01:36:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[01:36:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Version Information:
[01:36:57 ERROR]: #!#!   Skript: 2.6 (latest)
[01:36:57 ERROR]: #!#!     Flavor: skriptlang-github
[01:36:57 ERROR]: #!#!     Date: 17:20:35.482878100
[01:36:57 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[01:36:57 ERROR]: #!#!   Minecraft: 1.17.1
[01:36:57 ERROR]: #!#!   Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9)
[01:36:57 ERROR]: #!#!   OS: Linux amd64 5.11.0-38-generic
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Server platform: Paper
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Current node: null
[01:36:57 ERROR]: #!#! Current item: [skellett] load chunk %chunk% [[with] generat(e|ing) %-boolean%]
[01:36:57 ERROR]: #!#! Current trigger: command /start (simple event) (Islands.sk, line 1)
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Thread: Server thread
[01:36:57 ERROR]: #!#! 
[01:36:57 ERROR]: #!#! Language: english

**Comment by TheLimeGlass** [comment]
Please provide the coding you are using. The chunk used in the syntax was not set.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.6
