### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData

### ISSUE THREAD

**Issue by Minecon724** [TheLimeGlass/Skellett#152]
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at me.limeglass.skellett.elements.DefaultConverters.<clinit>(DefaultConverters.java:14) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:195) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:392) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:351) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:402) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:366) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:328) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:295) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:559) [NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:93) ~[NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:88) ~[NachoSpigot.jar:git-NachoSpigot-"2cefae4"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more

**Comment by MoTastisch** [comment]
same

**Comment by Nesb01t** [comment]
same

**Comment by TheLimeGlass** [comment]
Note: 1.8 related bug.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.6
