### ISSUE TITLE
ch.njol.skript.SkriptAPIException: No class info found for citizen

### ISSUE THREAD

**Issue by Yahumoo** [TheLimeGlass/Skellett#155]
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! [Skript] Severe Error:
[00:39:27 ERROR]: #!#! Could not load mapRotation.sk
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Something went horribly wrong with Skript.
[00:39:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:39:27 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:39:27 ERROR]: #!#! Here is full list of them:
[00:39:27 ERROR]: #!#! SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[00:39:27 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:39:27 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:39:27 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:39:27 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:39:27 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:39:27 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Stack trace:
[00:39:27 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[00:39:27 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[00:39:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[00:39:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1497)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[00:39:27 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Version Information:
[00:39:27 ERROR]: #!#!   Skript: 2.6.1 (latest)
[00:39:27 ERROR]: #!#!     Flavor: skriptlang-github
[00:39:27 ERROR]: #!#!     Date: 22:18:42.554713200
[00:39:27 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[00:39:27 ERROR]: #!#!   Minecraft: 1.18.1
[00:39:27 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[00:39:27 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Server platform: Paper
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Current node: if file "plugins/Skript/maps/maps.yml" doesn't exist: (mapRotation.sk, line 12)
[00:39:27 ERROR]: #!#! Current item: null
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Thread: Server thread
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Language: english
[00:39:27 ERROR]: #!#! Link parse mode: DISABLED
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! End of Error.
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! [Skript] Severe Error:
[00:39:27 ERROR]: #!#! Could not load stat.sk
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Something went horribly wrong with Skript.
[00:39:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:39:27 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:39:27 ERROR]: #!#! Here is full list of them:
[00:39:27 ERROR]: #!#! SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[00:39:27 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:39:27 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:39:27 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:39:27 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:39:27 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:39:27 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Stack trace:
[00:39:27 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[00:39:27 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[00:39:27 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[00:39:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[00:39:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1497)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
[00:39:27 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[00:39:27 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Version Information:
[00:39:27 ERROR]: #!#!   Skript: 2.6.1 (latest)
[00:39:27 ERROR]: #!#!     Flavor: skriptlang-github
[00:39:27 ERROR]: #!#!     Date: 22:18:42.554713200
[00:39:27 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[00:39:27 ERROR]: #!#!   Minecraft: 1.18.1
[00:39:27 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[00:39:27 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Server platform: Paper
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Current node: loop all players: (stat.sk, line 56)
[00:39:27 ERROR]: #!#! Current item: null
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Thread: Server thread
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! Language: english
[00:39:27 ERROR]: #!#! Link parse mode: DISABLED
[00:39:27 ERROR]: #!#!
[00:39:27 ERROR]: #!#! End of Error.
[00:39:27 ERROR]: #!#!

Skript: 2.6.1
Skellett: 2.0.3

**Comment by TheLimeGlass** [comment]
Are you using Citizens syntaxes? Do you have Citizens enabled in the config.yml?

**Comment by Yahumoo** [comment]
I don't know what is citizens syntaxes but I don't use citizens

**Comment by MrHipsterG** [comment]
I'm also running into this issue with most of my skripts.

**Comment by BaeFell** [comment]
This issue has been reported multiple times on the skUnity Discord. Appears not running Citizens breaks Skellett.

**Comment by the-najjar** [comment]
Same issue here, paper 1.18.1, skellet 2.0.3 skript 2.6.1, it breaks almost all of my skripts, please we need a fix for this, otherwise we can't use many of our skripts that were based on skellet.

**Comment by the-najjar** [comment]
Okay as nfell2009 mentioned the only fix for this right now is to enable citizen support from skellet config.yml and have citizen in ur plugins

**Comment by TheLimeGlass** [comment]
Duplicate and fixed in 2.0.4 https://github.com/TheLimeGlass/Skellett/issues/167
