### ISSUE TITLE
ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double

### ISSUE THREAD

**Issue by LeckererSandwich** [TheLimeGlass/Skellett#158]
i get this error message when i try to use any skellet features

[09:22:15 ERROR]: #!#! [Skript] Severe Error:
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:22:15 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[09:22:15 ERROR]: #!#! and check whether this error has already been reported.
[09:22:15 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[09:22:15 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:22:15 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:22:15 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! Stack trace:
[09:22:15 ERROR]: #!#! java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
[09:22:15 ERROR]: #!#!     at me.limeglass.skellett.elements.expressions.ExprAbsoluteValue.convert(ExprAbsoluteValue.java:7)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[09:22:15 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:181)
[09:22:15 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:22:15 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:22:15 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:22:15 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[09:22:15 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[09:22:15 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:22:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[09:22:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[09:22:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:407)
[09:22:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[09:22:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[09:22:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[09:22:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! Version Information:
[09:22:15 ERROR]: #!#!   Skript: 2.2-Mineplex-Core-Patch
[09:22:15 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[09:22:15 ERROR]: #!#!   Minecraft: 1.8.8
[09:22:15 ERROR]: #!#!   Java: 11.0.13 (Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370)
[09:22:15 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! Running CraftBukkit: false
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! Current node: null
[09:22:15 ERROR]: #!#! Current item: send "%the absolute value of [[long:-7]]%" to event-player/console
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! Thread: Server thread
[09:22:15 ERROR]: #!#!
[09:22:15 ERROR]: #!#! End of Error.

**Comment by TheLimeGlass** [comment]
Absolute value has been removed, Skript now has a built in function `abs(double)`
