### ISSUE TITLE
idk but i got this error with skellet. i removed skellet and the error fixed.

### ISSUE THREAD

**Issue by ansh096** [TheLimeGlass/Skellett#159]
`[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! [Skript] Severe Error:
[13:27:12 ERROR]: #!#! Could not load hub.sk
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Something went horribly wrong with Skript.
[13:27:12 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:27:12 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:27:12 ERROR]: #!#! Here is full list of them:
[13:27:12 ERROR]: #!#! SkBee v1.15.0 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[13:27:12 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:27:12 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:27:12 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:27:12 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:27:12 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:27:12 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Stack trace:
[13:27:12 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[13:27:12 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section.init(Section.java:69)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:46)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:138)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:721)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[13:27:12 ERROR]: #!#!     at Skript (5).jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[13:27:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:27:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:27:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
[13:27:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:27:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Version Information:
[13:27:12 ERROR]: #!#!   Skript: 2.6.1 (latest)
[13:27:12 ERROR]: #!#!     Flavor: skriptlang-github
[13:27:12 ERROR]: #!#!     Date: 22:18:42.554713200
[13:27:12 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[13:27:12 ERROR]: #!#!   Minecraft: 1.18.1
[13:27:12 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[13:27:12 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Server platform: Paper
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Current node: while {ip::%{_p}%} is not {_p}'s ip: (hub.sk, line 76)
[13:27:12 ERROR]: #!#! Current item: null
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Thread: Server thread
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! Language: english
[13:27:12 ERROR]: #!#! Link parse mode: DISABLED
[13:27:12 ERROR]: #!#!
[13:27:12 ERROR]: #!#! End of Error.
[13:27:12 ERROR]: #!#!`

**Comment by fiuipko** [comment]
bump i got same error on 1.18.2

**Comment by Henry-Bonikowsky** [comment]
The reason is because Skellet hasn't been updated to 1.18.2. We will have to wait before getting access to it on 1.18.2+ servers.

**Comment by TheLimeGlass** [comment]
Duplicate and fixed in 2.0.4 https://github.com/TheLimeGlass/Skellett/issues/167
