### ISSUE TITLE
Can't register the class info skellettteam because the class org.bukkit.scoreboard.Team is already registered

### ISSUE THREAD

**Issue by MarshallPatryk** [TheLimeGlass/Skellett#162]
Minecraft version: 1.18+
Engine: Paper
Plugins: Citizens, DeluxeMenus, Essentials, EssentialsSpawn, ItemsAdder, LibsDisguises, LoneLibs, PlaceholderAPI, ProtocolLib, Skacket, SkBee, Skellett, SkQuery, Skream, Skript, skript-db, UltraPermissions, Vault, WorldEdit, WorldGuard

Error:
`[19:02:47 INFO]: [Skellett] Enabling Skellett v2.0.3
[19:02:47 ERROR]: Error occurred while enabling Skellett v2.0.3 (Is it up to date?)
java.lang.IllegalArgumentException: Can't register the class info skellettteam because the class org.bukkit.scoreboard.Team is already registered
        at ch.njol.skript.registrations.Classes.registerClass(Classes.java:92) ~[Skript 2.6.1.jar:?]
        at com.gmail.thelimeglass.Register.types(Register.java:631) ~[Skellett-Legacy-2.0.3.jar:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:200) ~[Skellett-Legacy-2.0.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-259]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-259]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[19:02:47 INFO]: [Skellett] Disabling Skellett v2.0.3`

**Comment by MennoGamed** [comment]
I can confirm this.
The other functions of the plugin will continue to work, you will get this error when starting the server.

Here is a pastebin link: [click here](https://pastebin.com/pfWS6Vd0)

**Comment by yakkudev** [comment]
In my case the error didn't occur after removing Skream

**Comment by MennoGamed** [comment]
I don't use the addon "Skream".

**Comment by TheLimeGlass** [comment]
Can you test with the new Skellett version 2.0.4? If this issue still occurs, please state your addon list if it's different than mentioned. (You can disable scoreboards in the config.yml as well}

It's conflicting with another addon, but I don't know which addon, so i'll have to debug which.

**Comment by TheLimeGlass** [comment]
SkBee conflict, fixed in 2.0.4a
