### ISSUE TITLE
fall distance ERROR

### ISSUE THREAD

**Issue by loadka95** [TheLimeGlass/Skellett#17]
# Code: 
```
every tick in "world":
	loop {sping::*}:
		if fall distance of loop-value is greater than 10:
			teleport loop-value to {splegg.lobby}
			message "{@splegg}Lost." to loop-value
			subtract loop-value from {splegg::*}
```
# CONSOLE MESSAGE:

[14:52:58 ERROR]: #!#! [Skript] Severe Error:
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[14:52:58 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[14:52:58 ERROR]: #!#! and check whether this error has already been reported.
[14:52:58 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[14:52:58 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[14:52:58 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[14:52:58 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! Stack trace:
[14:52:58 ERROR]: #!#! java.lang.NullPointerException
[14:52:58 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprFallDistance.get(ExprFallDistance.java:47)
[14:52:58 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprFallDistance.get(ExprFallDistance.java:1)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:164)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:260)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:92)
[14:52:58 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$2.run(EvtPeriodical.java:116)
[14:52:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:52:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[14:52:58 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
[14:52:58 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[14:52:58 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[14:52:58 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[14:52:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! Version Information:
[14:52:58 ERROR]: #!#!   Skript: 2.2-dev23
[14:52:58 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[14:52:58 ERROR]: #!#!   Minecraft: 1.11.2
[14:52:58 ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[14:52:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! Running CraftBukkit: false
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! Current node: null
[14:52:58 ERROR]: #!#! Current item: [the] fall distance (from|of) %entity% is equal to [[long:10]] (comparator: ch.njol.skript.classes.data.DefaultComparators$1@49ec3cce)
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! Thread: Server thread
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#! End of Error.
[14:52:58 ERROR]: #!#!
[14:52:58 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Fixed in 1.7.7 (Next update) thanks for the bug report.
