### ISSUE TITLE
ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [player] fish[ing] [state[s] [of] %-fishingstates%]]

### ISSUE THREAD

**Issue by Charles-Mahoudeau** [TheLimeGlass/Skellett#170]
I have this error when using Skellett-Legacy-2.0.4a : 

```
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! [Skript] Severe Error:
10.06 16:04:27 [Server] ERROR #!#! Could not load tabCompleters.sk
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Something went horribly wrong with Skript.
10.06 16:04:27 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
10.06 16:04:27 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
10.06 16:04:27 [Server] ERROR #!#! Here is full list of them:
10.06 16:04:27 [Server] ERROR #!#! skRayFall v1.9.27 (https://sk.rayfall.net/) SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade) SkBee v1.15.3 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.4a (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.6 
10.06 16:04:27 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
10.06 16:04:27 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
10.06 16:04:27 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
10.06 16:04:27 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
10.06 16:04:27 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
10.06 16:04:27 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Stack trace:
10.06 16:04:27 [Server] ERROR #!#! ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [player] fish[ing] [state[s] [of] %-fishingstates%]]
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
10.06 16:04:27 [Server] ERROR #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1037)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1008)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
10.06 16:04:27 [Server] ERROR #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
10.06 16:04:27 [Server] ERROR #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for fishingstate
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:77)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
10.06 16:04:27 [Server] ERROR #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1037)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1008)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
10.06 16:04:27 [Server] ERROR #!#!     at Skript_4.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
10.06 16:04:27 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
10.06 16:04:27 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
10.06 16:04:27 [Server] ERROR #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Version Information:
10.06 16:04:27 [Server] ERROR #!#!   Skript: 2.6.2 (latest)
10.06 16:04:27 [Server] ERROR #!#!     Flavor: skriptlang-github
10.06 16:04:27 [Server] ERROR #!#!     Date: 19:12:53.596652600
10.06 16:04:27 [Server] ERROR #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
10.06 16:04:27 [Server] ERROR #!#!   Minecraft: 1.18.2
10.06 16:04:27 [Server] ERROR #!#!   Java: 17 (OpenJDK 64-Bit Server VM 17+20-202105042342)
10.06 16:04:27 [Server] ERROR #!#!   OS: Linux amd64 4.18.0-338.el8.x86_64
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Server platform: Paper
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Current node: on tab completer for "/selectcastlechunk": (tabCompleters.sk, line 1)
10.06 16:04:27 [Server] ERROR #!#! Current item: null
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Thread: Server thread
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! Language: english
10.06 16:04:27 [Server] ERROR #!#! Link parse mode: DISABLED
10.06 16:04:27 [Server] ERROR #!#! 
10.06 16:04:27 [Server] ERROR #!#! End of Error.
10.06 16:04:27 [Server] ERROR #!#!
```

Using Skript 2.6.2

**Addons :**
- Skellet v2.0.4a
- skRayFall v1.9.27
- skQuery v4.1.6
- SkBee v1.4.1

**Minecraft Version :** 1.18.2 (git-Paper-e0b3f3f)

**Comment by TheLimeGlass** [comment]
Not latest when you reported try 2.0.5.
