### ISSUE TITLE
When i add Skellet 2.0.5 its happen

### ISSUE THREAD

**Issue by moonetics** [TheLimeGlass/Skellett#171]
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! [Skript] Severe Error:
[09:30:45 ERROR]: #!#! Could not load playtime.sk
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Something went horribly wrong with Skript.
[09:30:45 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:30:45 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:30:45 ERROR]: #!#! Here is full list of them:
[09:30:45 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.27 (https://sk.rayfall.net/) SkBee v1.16.0 (https://github.com/ShaneBeee/SkBee) Skacket v1.0.10 Skellett v2.0.5 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 AuctionMaster v4.1 (https://discord.gg/nchk86TKMT) skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect) SkriptJSON v1.0.0 DiSky v4.0-beta4 skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.4 SkQuery v4.1.4 
[09:30:45 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:30:45 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:30:45 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:30:45 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:30:45 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:30:45 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Stack trace:
[09:30:45 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: com.gmail.thelimeglass.Scoreboards.ExprTeamFriendlyFire
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:529)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:30:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:30:45 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [the] [(score[ ][board]|[skellett[ ]]board)] friendly [fire] state [(for|of)] [team] %scoreboardteam%]
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[09:30:45 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:529)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:30:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:30:45 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for scoreboardteam
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[09:30:45 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lwang.SkriptParser.parse(SkriptParser.java:254)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[09:30:45 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:30:45 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[09:30:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:529)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[09:30:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:30:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Version Information:
[09:30:45 ERROR]: #!#!   Skript: 2.6.2 (latest)
[09:30:45 ERROR]: #!#!     Flavor: skriptlang-github
[09:30:45 ERROR]: #!#!     Date: 19:12:53.596652600
[09:30:45 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[09:30:45 ERROR]: #!#!   Minecraft: 1.17.1
[09:30:45 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[09:30:45 ERROR]: #!#!   OS: Linux amd64 5.4.0-1083-azure
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Server platform: Paper
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Current node: set {_minuteresult} to skutil yaml value "Playtime.minute" from file "{@file}/%player%-db.yml" (playtime.sk, line 6)
[09:30:45 ERROR]: #!#! Current item: null
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Thread: Server thread
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! Language: english
[09:30:45 ERROR]: #!#! Link parse mode: STRICT
[09:30:45 ERROR]: #!#! 
[09:30:45 ERROR]: #!#! End of Error.
[09:30:45 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Send your config.yml of Skellett too please.

**Comment by moonetics** [comment]
my config.yml of skellet

https://pastebin.com/1jdGns5Z

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.6
