### ISSUE TITLE
java.lang.RuntimeException: pattern compiling exception, element class: me.limeglass.skellett.elements.bossbars.ExprBossBarPlayers

### ISSUE THREAD

**Issue by moonetics** [TheLimeGlass/Skellett#175]
[23:49:30 ERROR]: #!#! [Skript] Severe Error:
[23:49:30 ERROR]: #!#! Could not load topvoter.sk
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Something went horribly wrong with Skript.
[23:49:30 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:49:30 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:49:30 ERROR]: #!#! Here is full list of them:
[23:49:30 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.27 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkriptJSON v1.0.0 DiSky v4.0-beta4 skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.6 Skellett v2.0.6 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 AuctionMaster v4.1 (https://discord.gg/nchk86TKMT) DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) 
[23:49:30 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:49:30 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:49:30 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:49:30 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:49:30 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:49:30 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Stack trace:
[23:49:30 ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: me.limeglass.skellett.elements.bossbars.ExprBossBarPlayers
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:49:30 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:49:30 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [all [of]] [the] players (from|of) [[boss][ ]bar] %bossbars%]
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[23:49:30 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:49:30 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:49:30 ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for bossbar
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[23:49:30 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[23:49:30 ERROR]: #!#!     at Skript 2.6.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:49:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1229)
[23:49:30 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:49:30 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Version Information:
[23:49:30 ERROR]: #!#!   Skript: 2.6.2 (latest)
[23:49:30 ERROR]: #!#!     Flavor: skriptlang-github
[23:49:30 ERROR]: #!#!     Date: 19:12:53.596652600
[23:49:30 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[23:49:30 ERROR]: #!#!   Minecraft: 1.17.1
[23:49:30 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[23:49:30 ERROR]: #!#!   OS: Linux amd64 5.4.0-1083-azure
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Server platform: Paper
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Current node: send request to uncolored "https://minecraft-mp.com/api/?object=servers&&eelement=voters&&kkey=mUxjWMJB5nJBYIj9kaEE7MecvIob6DF8ben&&mmonth=previous&&fformat=json" (topvoter.sk, line 2)
[23:49:30 ERROR]: #!#! Current item: null
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Thread: Server thread
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! Language: english
[23:49:30 ERROR]: #!#! Link parse mode: STRICT
[23:49:30 ERROR]: #!#! 
[23:49:30 ERROR]: #!#! End of Error.
[23:49:30 ERROR]: #!#!

My config of skellet: https://pastebin.com/3aP05k75

**Comment by TheLimeGlass** [comment]
Can you send your topvoter.sk file

**Comment by TheLimeGlass** [comment]
Send a full list of your addons please.

**Comment by moonetics** [comment]
> Send a full list of your addons please.

DiSky 4.0beta4
Reqn 1.2.1
Skacket 1.0.10
skBee 1.16.3
skQuery 4.1.6
Skellet 2.0.6
skRayFall 1.9.27
skript-json 1.1.1
skript-placeholder 1.5.2
skript-reflect 2.3
skUtilities 0.9.2
skript-yaml 1.4

**Comment by ghost** [comment]
Skellet is causing problems with a bossbar - skript. Send your skript file that is using both bossbars and skellet.

**Comment by ghost** [comment]
**This line is the issue.**
23:49:30 ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [all [of]] [the] players (from|of) [[boss][ ]bar] %bossbars%]

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.9
