### ISSUE TITLE
Skbee v2.4.0 and up breaks skellet

### ISSUE THREAD

**Issue by Retasukah** [TheLimeGlass/Skellett#193]
[23:25:38 ERROR]: Error occurred while enabling Skellett v2.0.8 (Is it up to date?)
java.lang.IllegalArgumentException: Can't register net.md_5.bungee.api.chat.TextComponent with the code name textcomponent because that name is already used by text component
	at ch.njol.skript.registrations.Classes.registerClass(Classes.java:91) ~[Skript.jar:?]
	at com.gmail.thelimeglass.Register.types(Register.java:496) ~[Skellett-Legacy-2.0.8.jar:?]
	at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:182) ~[Skellett-Legacy-2.0.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-215]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-215]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Retasukah** [comment]
disabling text components fixes this

**Comment by garbi23** [comment]
how to disable text component?

**Comment by ghost** [comment]
Open SkBee's config file and you should be able to disable it there.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.9
