### ISSUE TITLE
Citizens Hook Error

### ISSUE THREAD

**Issue by mrpetfreak** [TheLimeGlass/Skellett#25]
Got an error using Citizens version 2.0.16 and Skellett version 1.8.1:

`[18:40:26] [Server thread/ERROR]: Error occurred while enabling Skellett v1.8.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/NPCEnderTeleportEvent
	at com.gmail.thelimeglass.Register.events(Register.java:471) ~[?:?]
	at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:301) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Dev.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [Dev.jar:git-Spigot-6d16e64-87b9f46]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.NPCEnderTeleportEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Dev.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Dev.jar:git-Spigot-6d16e64-87b9f46]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`

**Comment by TheLimeGlass** [comment]
You will need to update your citizens. You can find builds here http://ci.citizensnpcs.co/
