### ISSUE TITLE
MySQL - Password

### ISSUE THREAD

**Issue by Quaczi** [TheLimeGlass/Skellett#62]
[21:17:44 INFO]: [Skript] Reloading my.sk...
[21:17:44 ERROR]: Can't understand this condition/effect: set mysql password to "PASSWORD" (my.sk, line 4: set mysql password to "PASSWORD"')
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! [Skript] Severe Error:
[21:17:44 ERROR]: #!#! Could not load my.sk
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:17:44 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[21:17:44 ERROR]: #!#! and check whether this error has already been reported.
[21:17:44 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[21:17:44 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:17:44 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:17:44 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! Stack trace:
[21:17:44 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for resultset
[21:17:44 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1394)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1115)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1127)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:320)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:417)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1136)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1127)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:650)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:268)
[21:17:44 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155)
[21:17:44 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:17:44 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[21:17:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[21:17:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
[21:17:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416)
[21:17:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[21:17:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[21:17:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[21:17:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! Version Information:
[21:17:44 ERROR]: #!#!   Skript: 2.2-Fixes-V8b
[21:17:44 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[21:17:44 ERROR]: #!#!   Minecraft: 1.8.8
[21:17:44 ERROR]: #!#!   Java: 1.8.0_144 (Java HotSpot(TM) Client VM 25.144-b01)
[21:17:44 ERROR]: #!#!   OS: Windows 7 x86 6.1
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! Running CraftBukkit: false
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! Current node: set {_final} to mysql string "Customers" in {_test} (my.sk, line 8)
[21:17:44 ERROR]: #!#! Current item: null
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! Thread: Server thread
[21:17:44 ERROR]: #!#!
[21:17:44 ERROR]: #!#! End of Error.
[21:17:44 ERROR]: #!#!
[21:17:44 INFO]: [Skript] Encountered 1 error while reloading my.sk!

If it doesn't send any errors then it just not connecting to MySQL

**Comment by TheLimeGlass** [comment]
You need to enable the MySQL password syntax in the MySQL.yml
