### ISSUE TITLE
dev32 seems to break mysql support

### ISSUE THREAD

**Issue by melinstagibson** [TheLimeGlass/Skellett#65]
code that worked in dev31c now throws this super severe whatever error

here is the skript part (this happens to all my select queries in all my skripts with dev32)

```
function isonline(p: string) :: boolean:
        set {_r} to mysql result of query "SELECT server FROM playerdata.status WHERE ign='%{_p}%' and (faction=true or safe=true or vanilla=true or lobby=true)"
        set {_rr} to first element of mysql string "server" in {_r}
        if {_rr} is set:
                return true
        else:
                return false
```
and here is the error
```
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! [Skript] Severe Error:
[20:21:04 ERROR]: #!#! Could not load duel.sk
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! Something went horribly wrong with Skript.
[20:21:04 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:21:04 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:21:04 ERROR]: #!#! Here is full list of them:
[20:21:04 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) SkStuff SkQuery Skellett (https://forums.skunity.c
om/resources/skellett-the-addon-with-a-beast-name.24/) MundoSK (https://forums.skunity.com/resources/mundosk.69/) SharpSK
[20:21:04 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:21:04 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:21:04 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:21:04 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:21:04 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:21:04 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[20:21:04 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! Stack trace:
[20:21:04 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for resultset
[20:21:04 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1786)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1753)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1501)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:52)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:134)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:584)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[20:21:56 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:21:56 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[20:21:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[20:21:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:639)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[20:21:56 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Version Information:
[20:21:56 ERROR]: #!#!   Skript: 2.2-dev32 (latest)
[20:21:56 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[20:21:56 ERROR]: #!#!   Minecraft: 1.12.2
[20:21:56 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[20:21:56 ERROR]: #!#!   OS: Linux amd64 4.10.0-22-generic
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Running CraftBukkit: false
[20:21:56 ERROR]: #!#! Running Spigot (or compatible): true
[20:21:56 ERROR]: #!#! Running Paper (or compatible): true
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Current node: set {_rr} to first element of mysql string "server" in {_r} (duel.sk, line 7)
[20:21:56 ERROR]: #!#! Current item: null
[20:21:56 ERROR]: #!#! Thread: Server thread
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Language: english
[20:21:56 ERROR]: #!#! Link parse mode: DISABLED
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! End of Error.```

**Comment by Tai1er** [comment]
Same problem with dev30, dev31 and dev32.
The expression "mysql string/integer/etc in" are broken in 1.12.2.

**Comment by melinstagibson** [comment]
dev31 works for me with 1.12.2 but im not on the latest spigot/paper version

**Comment by Tai1er** [comment]
Same problem with dev31 and the first 1.12.2 version of PaperSpigot. Which is your Paper version?

**Comment by TheLimeGlass** [comment]
Thanks for reporting this. I know about this issue, and I might make a new addon for MySQL. For now you can use https://forums.skunity.com/resources/skript-db.372/
