### ISSUE TITLE
Can't connect Skellett and SkellettProxy

### ISSUE THREAD

**Issue by onxzy** [TheLimeGlass/Skellett#68]
Hi.
I've setup Skellett and SkellettProxy like it's said in the tutorial (same port, localhost, ...) but i've alway get this error :
```
20:05:37 [INFOS] Lobby > [Skellett] Attempting to reconnect and fix myself...
20:05:37 [INFOS] Lobby > [Skellett] Bungeecord went offline. Attempting to reconnect...
20:05:37 [AVERTISSEMENT] Lobby > java.io.EOFException
20:05:37 [AVERTISSEMENT] Lobby > at java.io.ObjectInputStream$BlockDataInputStream.peekByte(Unknown Source)
20:05:37 [AVERTISSEMENT] Lobby > at java.io.ObjectInputStream.readObject0(Unknown Source)
20:05:37 [AVERTISSEMENT] Lobby > at java.io.ObjectInputStream.readObject(Unknown Source)
20:05:37 [AVERTISSEMENT] Lobby > at com.gmail.thelimeglass.Sockets.connect(Sockets.java:69)
20:05:37 [AVERTISSEMENT] Lobby > at com.gmail.thelimeglass.Sockets$1.run(Sockets.java:27)
20:05:37 [AVERTISSEMENT] Lobby > at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
20:05:37 [AVERTISSEMENT] Lobby > at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
20:05:37 [AVERTISSEMENT] Lobby > at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
20:05:37 [AVERTISSEMENT] Lobby > at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
20:05:37 [AVERTISSEMENT] Lobby > at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
20:05:37 [AVERTISSEMENT] Lobby > at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
20:05:37 [AVERTISSEMENT] Lobby > at java.lang.Thread.run(Unknown Source)
20:05:37 [INFOS] Lobby > [Skellett] SkellettProxy connection established on port 25556
20:05:37 [INFOS] Lobby > [Skellett] Incorrect SkellettProxy details, No socket found or was denied access. For socket at 0.0.0.0:12345
20:05:37 [GRAVE] Lobby > [Skript] If you're 100% sure your details are correct, this can be caused because some server's want a number host rather than localhost. Try inserting 0.0.0.0 or 127.0.0.1 instead of localhost. Error:  (config.sk, line 184: databases:')
```
I've tried different way like resetup, change by 0.0.0.0 or 127.0.0.1 or my computer ip adress and this still doesn't work. For info i use Subservers if the problem come from that.
I'm very exited about testing all the features, but for the moment i cant cause of that problem.
Have a nice day
(I'm sorry for the fault, i'm not english)

**Comment by TheLimeGlass** [comment]
Please use Skungee as that is the newer more updated Bungeecord addon https://www.spigotmc.org/resources/skript-java-addon-skungee-bungeecord-addon-for-skript.35636/
