### ISSUE TITLE
BungeeChatAPI Issue

### ISSUE THREAD

**Issue by EazyFTW** [TheLimeGlass/Skellett#69]
```
[09:51:14 ERROR]: Error occurred while enabling Skellett v1.9.6b (Is it up to date?)
java.lang.IllegalArgumentException: Can't register net.md_5.bungee.api.chat.TextComponent with the code name textcomponent because that name is already used by types.textcomponent
        at ch.njol.skript.registrations.Classes.registerClass(Classes.java:91) ~[?:?]
        at com.gmail.thelimeglass.Register.types(Register.java:793) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-06f33d0-86fdf92]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-06f33d0-86fdf92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

```

It is making my skript cause errors it should be like bossbar errors.

**Comment by EazyFTW** [comment]
Deleting the folder (Skellet folder in plugins folder) and restarting fixed.....

**Comment by TheLimeGlass** [comment]
May you please provide other addons/plugins you may be using? It's conflicting with another type from an addon.

**Comment by EazyFTW** [comment]
This is an old issue. I'm not using Bungee Skellet anymore and I see you updated the plugin so it could be fixed.
