### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HYPExMon5ter** [TheLimeGlass/Skellett#70]
[01:11:34] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Skellett v1.9.6a
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.util.NoSuchElementException: packet_handler
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
    at com.comphenix.protocol.injector.netty.ChannelInjector$5$1.addBefore(ChannelInjector.java:297) ~[?:?]
    at com.gmail.thelimeglass.Utils.Packets.PacketListener.create(PacketListener.java:70) ~[?:?]
    at com.gmail.thelimeglass.Utils.Packets.PacketListener.onJoin(PacketListener.java:22) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-latest-build.jar:git-Spigot-3fb9445-6e3cec8]
    ... 14 more

**Comment by TheLimeGlass** [comment]
Similar duplicate to #71 will look into this strange bug with packets. You can disable packets to fix this issue from happening to allow for Skellett to load.
