### ISSUE TITLE
Collide state 

### ISSUE THREAD

**Issue by andrei923** [TheLimeGlass/Skellett#73]
`[01:52:09 ERROR]: Could not pass event PlayerJoinEvent to Skript v2.2-dev27
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.setCollidable(Z)V
        at com.gmail.thelimeglass.Effects.EffSetCollidable.execute(EffSetCollidable.java:35) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:107) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:189) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:107) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:189) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

- CODE

`function sg_setspec(p: player):	
	set collide state of {_p} to false	`

**Comment by TheLimeGlass** [comment]
The collide state doesn't exist for your 1.8 server. I suggest not using it or updating your spigot. I will add a version catcher to Skellett 2.0 to not register this syntax if this version is present. May you please provide your 1.8 version by typing `/version`

**Comment by UzumakiYT** [comment]
last 1.8.8 version - spigot.

**Comment by TheLimeGlass** [comment]
Fixed in the next version
