### ISSUE TITLE
Skript Skellet Error

### ISSUE THREAD

**Issue by Romanthefrog10** [TheLimeGlass/Skellett#76]
```
[15:44:52 ERROR]: #!#! Stack trace:
[15:44:52 ERROR]: #!#! java.lang.NullPointerException
[15:44:52 ERROR]: #!#!     at com.gmail.thelimeglass.Books.BungeeJson.EffAddComponentToPage.execute(EffAddComponentToPage.java:45)
[15:44:52 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[15:44:52 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[15:44:52 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[15:44:52 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[15:44:52 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:44:52 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:44:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[15:44:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:44:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:44:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:44:52 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:44:52 ERROR]: #!#!
[15:44:52 ERROR]: #!#! Version Information:
[15:44:52 ERROR]: #!#!   Skript: 2.2-dev22f
[15:44:52 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:44:52 ERROR]: #!#!   Minecraft: 1.8.8
[15:44:52 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[15:44:52 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:44:52 ERROR]: #!#!
[15:44:52 ERROR]: #!#! Running CraftBukkit: false
[15:44:52 ERROR]: #!#!
[15:44:52 ERROR]: #!#! Current node: null
[15:44:52 ERROR]: #!#! Current item: add text component %textcomponents% to [book] %itemstack%
[15:44:52 ERROR]: #!#!
[15:44:52 ERROR]: #!#! Thread: Server thread
[15:44:52 ERROR]: #!#!
[15:44:52 ERROR]: #!#! End of Error.
```
I keep getting that error does anyone know how to fix and what the problem is?

**Comment by TheLimeGlass** [comment]
The text component is null or the itemstack book is null. Meaning not set. Make sure you have these values set.

**Comment by TheLimeGlass** [comment]
Fixed in the next version

**Comment by rsiebertdev** [comment]
*1.8 years later... o\-\o (Posted this in January 2018 and its only fixed now..)*
