### ISSUE TITLE
Play Sound Error

### ISSUE THREAD

**Issue by Techno3600** [TheLimeGlass/Skellett#77]
This happens whenever I try to do a command that involves sound.
```
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! [Skript] Severe Error:
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Something went horribly wrong with Skript.
08.01 16:07:27 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
08.01 16:07:27 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
08.01 16:07:27 [Server] ERROR #!#! Here is full list of them:
08.01 16:07:27 [Server] ERROR #!#! Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) 
08.01 16:07:27 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
08.01 16:07:27 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
08.01 16:07:27 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
08.01 16:07:27 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
08.01 16:07:27 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
08.01 16:07:27 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
08.01 16:07:27 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Stack trace:
08.01 16:07:27 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:66)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:150)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:75)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
08.01 16:07:27 [Server] ERROR #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164)
08.01 16:07:27 [Server] ERROR #!#!     at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
08.01 16:07:27 [Server] ERROR #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.01 16:07:27 [Server] ERROR #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
08.01 16:07:27 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
08.01 16:07:27 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
08.01 16:07:27 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
08.01 16:07:27 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
08.01 16:07:27 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08.01 16:07:27 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
08.01 16:07:27 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
08.01 16:07:27 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Version Information:
08.01 16:07:27 [Server] ERROR #!#!   Skript: 2.2-dev32c (latest)
08.01 16:07:27 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
08.01 16:07:27 [Server] ERROR #!#!   Minecraft: 1.12.2
08.01 16:07:27 [Server] ERROR #!#!   Java: 1.8.0_152 (Java HotSpot(TM) 64-Bit Server VM 25.152-b16)
08.01 16:07:27 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Running CraftBukkit: false
08.01 16:07:27 [Server] ERROR #!#! Running Spigot (or compatible): true
08.01 16:07:27 [Server] ERROR #!#! Running Paper (or compatible): false
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Current node: null
08.01 16:07:27 [Server] ERROR #!#! Current item: play sound
08.01 16:07:27 [Server] ERROR #!#! Thread: Server thread
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! Language: english
08.01 16:07:27 [Server] ERROR #!#! Link parse mode: DISABLED
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:27 [Server] ERROR #!#! End of Error.
08.01 16:07:27 [Server] ERROR #!#! 
08.01 16:07:29 [Server] INFO HIJACKED TechBlock102: then
08.01 16:07:33 [Server] INFO WIZ Techno3600: Well
08.01 16:07:39 [Server] INFO WIZ Techno3600: That was anti-climaxtic
08.01 16:07:45 [Server] INFO Deathmatch> DEATH MATCH IN 10...
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! [Skript] Severe Error:
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Something went horribly wrong with Skript.
08.01 16:07:45 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
08.01 16:07:45 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
08.01 16:07:45 [Server] ERROR #!#! Here is full list of them:
08.01 16:07:45 [Server] ERROR #!#! Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) 
08.01 16:07:45 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
08.01 16:07:45 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
08.01 16:07:45 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
08.01 16:07:45 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
08.01 16:07:45 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
08.01 16:07:45 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
08.01 16:07:45 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Stack trace:
08.01 16:07:45 [Server] ERROR #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:66)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:150)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:75)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
08.01 16:07:45 [Server] ERROR #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164)
08.01 16:07:45 [Server] ERROR #!#!     at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
08.01 16:07:45 [Server] ERROR #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.01 16:07:45 [Server] ERROR #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
08.01 16:07:45 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
08.01 16:07:45 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
08.01 16:07:45 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
08.01 16:07:45 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
08.01 16:07:45 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08.01 16:07:45 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
08.01 16:07:45 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
08.01 16:07:45 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Version Information:
08.01 16:07:45 [Server] ERROR #!#!   Skript: 2.2-dev32c (latest)
08.01 16:07:45 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
08.01 16:07:45 [Server] ERROR #!#!   Minecraft: 1.12.2
08.01 16:07:45 [Server] ERROR #!#!   Java: 1.8.0_152 (Java HotSpot(TM) 64-Bit Server VM 25.152-b16)
08.01 16:07:45 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Running CraftBukkit: false
08.01 16:07:45 [Server] ERROR #!#! Running Spigot (or compatible): true
08.01 16:07:45 [Server] ERROR #!#! Running Paper (or compatible): false
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Current node: null
08.01 16:07:45 [Server] ERROR #!#! Current item: play sound
08.01 16:07:45 [Server] ERROR #!#! Thread: Server thread
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! Language: english
08.01 16:07:45 [Server] ERROR #!#! Link parse mode: DISABLED
08.01 16:07:45 [Server] ERROR #!#! 
08.01 16:07:45 [Server] ERROR #!#! End of Error.
08.01 16:07:45 [Server] ERROR #!#! 
```

**Comment by TheLimeGlass** [comment]
Can you provide your coding? This is an issue with Skript not Skellett.

**Comment by Techno3600** [comment]
When you say 'coding' what are you referring to?

**Comment by TheLimeGlass** [comment]
This syntax is in Vanilla Skript now.
