### ISSUE TITLE
Entity from UUID doesn't work

### ISSUE THREAD

**Issue by Xentax5** [TheLimeGlass/Skellett#78]
Hi, i tried to use entity from uuid syntax, but it keeps throwing me errors. Tried updating Skellett to newest version, didn't help.
Testing code for this syntax:

```
command /testuuid:
    trigger:
        broadcast "%UUID of player%"
        set {_uuid} to uuid of player
        set {_player} to entity from uuid {_uuid}
        broadcast "%UUID of player% = %{_player}%"
```

Error when i issued the command:
```
[13:11:23 INFO]: Xentax5 issued server command: /testuuid
[13:11:23 INFO]: Xentax5 [e3318548-cda6-3fed-8418-394c4cee1175]: /testuuid
[13:11:23 INFO]: e3318548-cda6-3fed-8418-394c4cee1175
[13:11:23 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-Fixes-V9b
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1149) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:992) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getEntity(Ljava/util/UUID;)Lorg/bukkit/entity/Entity;
at com.gmail.thelimeglass.Expressions.ExprEntityFromUUID.get(ExprEntityFromUUID.java:53) ~[?:?]
at com.gmail.thelimeglass.Expressions.ExprEntityFromUUID.get(ExprEntityFromUUID.java:1) ~[?:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
at ch.njol.skript.effects.EffChange.execute(EffChange.java:271) ~[?:?]
at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
at ch.njol.skript.command.Commands.handleCommand(Commands.java:270) ~[?:?]
at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]
at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
... 16 more
[13:11:23 INFO]: e3318548-cda6-3fed-8418-394c4cee1175
[13:11:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'testuuid' in plugin Skript v2.2-Fixes-V9b
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1157) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:992) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getEntity(Ljava/util/UUID;)Lorg/bukkit/entity/Entity;
at com.gmail.thelimeglass.Expressions.ExprEntityFromUUID.get(ExprEntityFromUUID.java:53) ~[?:?]
at com.gmail.thelimeglass.Expressions.ExprEntityFromUUID.get(ExprEntityFromUUID.java:1) ~[?:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
at ch.njol.skript.effects.EffChange.execute(EffChange.java:271) ~[?:?]
at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:161) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
... 15 more
```
Server version: 1.8.8
Skript version: Skript v2.2-Fixes-V9b
Skellett version: 1.9.5

**Comment by TheLimeGlass** [comment]
It's uuid from an entity not s uuid from uuid...

set {_example} to UUID from target entity

**Comment by Xentax5** [comment]
Hey i meant this:
`[skellett] entity (from [the]|of) (uuid|[universal] unique id) %string%`
check here https://docs.skunity.com/syntax/search/entity%20from%20u
