### ISSUE TITLE
Error: Enabling Particle Syntax

### ISSUE THREAD

**Issue by policiu** [TheLimeGlass/Skellett#8]
I was looking through the SkUnity docs and I saw syntax for particles with Skellett. Unfortunately, I cannot figure out how to get them to work. I couldn't find anything on the SkUnity forms about the particles.

Method:
Changing false to true in the SyntaxToggles.yml

Skript version: 2.2-dev36
Skellett version: 1.9.6b

> [16:52:35 ERROR]: Error occurred while enabling Skellett v1.9.6b (Is it up to date?)
java.lang.NoSuchFieldError: DEV_BUILD
        at com.gmail.thelimeglass.Register.types(Register.java:1027) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by TheLimeGlass** [comment]
I suggest not using the particle system from Skellett. Spigot API sucks besides you have Bensku's edit, just use the particles from Bensku's edit.
