### ISSUE TITLE
Error (Sounds)

### ISSUE THREAD

**Issue by UzumakiYT** [TheLimeGlass/Skellett#80]
[23:41:44 ERROR]: #!#! Something went horribly wrong with Skript.
[23:41:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:41:44 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[23:41:44 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[23:41:44 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[23:41:44 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[23:41:44 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! Stack trace:
[23:41:44 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for visualeffect
[23:41:44 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1788)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1755)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1503)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1476)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:52)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:134)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:584)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[23:41:44 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:444)
[23:41:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:41:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[23:41:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[23:41:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[23:41:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:41:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:41:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! Version Information:
[23:41:44 ERROR]: #!#!   Skript: 2.2-dev32d
[23:41:44 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[23:41:44 ERROR]: #!#!   Minecraft: 1.8.8
[23:41:44 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[23:41:44 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! Running CraftBukkit: false
[23:41:44 ERROR]: #!#! Running Spigot (or compatible): true
[23:41:44 ERROR]: #!#! Running Paper (or compatible): false
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! Current node: play sound "%{_sound}%" to {_p} with volume {_volume} and pitch {_pitch} (LeafSG.sk, line 948)
[23:41:44 ERROR]: #!#! Current item: null
[23:41:44 ERROR]: #!#! Thread: Server thread
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! Language: english
[23:41:44 ERROR]: #!#! Link parse mode: DISABLED
[23:41:44 ERROR]: #!#!
[23:41:44 ERROR]: #!#! End of Error.
[23:41:44 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Update your Skript to Bensku's edit

**Comment by UzumakiYT** [comment]
its last version of Bensku

**Comment by TheLimeGlass** [comment]
It's not a Skellett problem as Skellett doesn't have that type. It's from Skript. Downgrade if Bensku released a new version idk of.

**Comment by TheLimeGlass** [comment]
Try a different Spigot version aswell

**Comment by UzumakiYT** [comment]
its works with 2.2-dev27 (last 1.8.8 ver).

but not work on dev32d.

dev32d - "Made this fork run on 1.8.8 servers; still not supported (thanks
to @Pikachu920)"

2018-01-26 23:49 GMT+02:00 LimeGlass <notifications@github.com>:
