### ISSUE TITLE
Ground State

### ISSUE THREAD

**Issue by andrei923** [TheLimeGlass/Skellett#82]
on entity shoot:
	while ground state of shot projectile is false:
		wait 2 ticks
	broadcast "%shot projectile%"

[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! [Skript] Severe Error:
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[04:09:42 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[04:09:42 ERROR]: #!#! and check whether this error has already been reported.
[04:09:42 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[04:09:42 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[04:09:42 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[04:09:42 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! Stack trace:
[04:09:42 ERROR]: #!#! java.lang.NullPointerException
[04:09:42 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprGroundState.get(ExprGroundState.java:46)
[04:09:42 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprGroundState.get(ExprGroundState.java:1)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:157)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.lang.While.walk(While.java:48)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[04:09:42 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[04:09:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[04:09:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[04:09:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[04:09:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:246)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.ItemBow.a(ItemBow.java:61)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.ItemStack.b(ItemStack.java:520)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.EntityHuman.bU(EntityHuman.java:108)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:605)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[04:09:42 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[04:09:42 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[04:09:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[04:09:42 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! Version Information:
[04:09:42 ERROR]: #!#!   Skript: 2.2-dev27
[04:09:42 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[04:09:42 ERROR]: #!#!   Minecraft: 1.8.8
[04:09:42 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[04:09:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! Running CraftBukkit: false
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! Current node: null
[04:09:42 ERROR]: #!#! Current item: while [(is|are)] [on] [the] ground [state] [of] [entity] %entity% is equal to [[boolean:false]] (comparator: ch.njol.skript.classes.Comparator$1@22e9c303)
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! Thread: Server thread
[04:09:42 ERROR]: #!#!
[04:09:42 ERROR]: #!#! End of Error.
[04:09:42 ERROR]: #!#!

**Comment by UzumakiYT** [comment]
replaced while ground state of shot projectile is false:
with
while ground state of projectile is false:

and works fine now.

**Comment by UzumakiYT** [comment]
but there is other problem, when you hit someone with the arrow, the while will not stop.

**Comment by TheLimeGlass** [comment]
This syntax is in Skript now.
