### ISSUE TITLE
damage delay not working

### ISSUE THREAD

**Issue by Elioot** [TheLimeGlass/Skellett#90]
I have been trying to remove damage delay with 

on damage:
     set damage delay of victim to 1 tick

it was throwing this in the console:

[17:08:03 ERROR]: #!#! [Skript] Severe Error:
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Something went horribly wrong with Skript.
[17:08:03 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:08:03 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:08:03 ERROR]: #!#! Here is full list of them:
[17:08:03 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/)
[17:08:03 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:08:03 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:08:03 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:08:03 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:08:03 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:08:03 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Stack trace:
[17:08:03 ERROR]: #!#! java.lang.NullPointerException
[17:08:03 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprMaxDamageTicks.change(ExprMaxDamageTicks.java:55)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[17:08:03 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[17:08:03 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:08:03 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:08:03 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:231)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:990)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:972)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1045)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1031)
[17:08:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1027)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.EntityItem.damageEntity(EntityItem.java:261)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.EntityItem.burn(EntityItem.java:250)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:693)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.EntityItem.tick(EntityItem.java:89)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.World.a(World.java:936)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:472)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[17:08:03 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[17:08:03 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Version Information:
[17:08:03 ERROR]: #!#!   Skript: 2.4.1 (latest)
[17:08:03 ERROR]: #!#!     Flavor: skriptlang-github
[17:08:03 ERROR]: #!#!     Date: 2019-12-22
[17:08:03 ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:08:03 ERROR]: #!#!   Minecraft: 1.14.4
[17:08:03 ERROR]: #!#!   Java: 1.8.0_231 (Java HotSpot(TM) 64-Bit Server VM 25.231-b11)
[17:08:03 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Server platform: Paper
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Current node: null
[17:08:03 ERROR]: #!#! Current item: set [maximum] damage delay of %entity% to [[timespan:0.05 seconds]]
[17:08:03 ERROR]: #!#! Current trigger: damage (damage) (earth.sk, line 430)
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Thread: Server thread
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! Language: english
[17:08:03 ERROR]: #!#! Link parse mode: DISABLED
[17:08:03 ERROR]: #!#!
[17:08:03 ERROR]: #!#! End of Error.
[17:08:03 ERROR]: #!#!

so then I removed all the other plugins and the error persists and the skript still does not work
I am clueless rn and I think it is related to a skellett bug so I posted it here.

**Comment by Elioot** [comment]
forgot to mention I am running the latest version of skript and skellett for paper 1.14.4

**Comment by TheLimeGlass** [comment]
Entity was not set when you used this syntax. The error being thrown has been fixed in 1.9.9 but it won't make the syntax work, it's not working because you didn't set the entity.

**Comment by Elioot** [comment]
Could you tell me how to set the entity, because I still might want to use
this. I am confused.
