### ISSUE TITLE
Skellet error - Current item: [skellett] [force] respawn %player%

### ISSUE THREAD

**Issue by Loofn** [TheLimeGlass/Skellett#91]
So I got this error printed to my console from Skellet

> [09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! [Skript] Severe Error:
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Something went horribly wrong with Skript.
[09:52:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:52:19 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:52:19 ERROR]: #!#! Here is full list of them:
[09:52:19 ERROR]: #!#! SkQuery v4.1.1 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/)
[09:52:19 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:52:19 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:52:19 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:52:19 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:52:19 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:52:19 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Stack trace:
[09:52:19 ERROR]: #!#! java.lang.NullPointerException
[09:52:19 ERROR]: #!#! at com.gmail.thelimeglass.Effects.EffForceRespawn.execute(EffForceRespawn.java:32)
[09:52:19 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[09:52:19 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:52:19 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:52:19 ERROR]: #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[09:52:19 ERROR]: #!#! at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[09:52:19 ERROR]: #!#! at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[09:52:19 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[09:52:19 ERROR]: #!#! at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[09:52:19 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[09:52:19 ERROR]: #!#! at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[09:52:19 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Version Information:
[09:52:19 ERROR]: #!#! Skript: 2.5-alpha1 (latest)
[09:52:19 ERROR]: #!#! Flavor: skriptlang-github
[09:52:19 ERROR]: #!#! Date: 2020-01-11
[09:52:19 ERROR]: #!#! Bukkit: 1.15.2-R0.1-SNAPSHOT
[09:52:19 ERROR]: #!#! Minecraft: 1.15.2
[09:52:19 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
[09:52:19 ERROR]: #!#! OS: Linux amd64 4.15.0-66-generic
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Server platform: Paper
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Current node: null
[09:52:19 ERROR]: #!#! Current item: [skellett] [force] respawn %player%
[09:52:19 ERROR]: #!#! Current trigger: death (death/spawn) (kuolema.sk, line 6)
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Thread: Server thread
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! Language: english
[09:52:19 ERROR]: #!#! Link parse mode: DISABLED
[09:52:19 ERROR]: #!#!
[09:52:19 ERROR]: #!#! End of Error.
[09:52:19 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
This effect is now in Skript.
